import "./globals.css";
import { Inter } from "next/font/google";

// components
import NavBar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Apps",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="text-3xl">My Apps</h1>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
